### ISSUE TITLE
Add support for building with GCC

### ISSUE THREAD

**Issue by akzi** [jgilchrist/emulator#1]
fuwangqin@fuwangqin-pc:\~/code/emulator$ make
-- Found SFML 2.3.2 in /usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fuwangqin/code/emulator/build
make[1]: Entering directory '/home/fuwangqin/code/emulator/build'
make[2]: Entering directory '/home/fuwangqin/code/emulator/build'
make[3]: Entering directory '/home/fuwangqin/code/emulator/build'
Scanning dependencies of target emulator
make[3]: Leaving directory '/home/fuwangqin/code/emulator/build'
make[3]: Entering directory '/home/fuwangqin/code/emulator/build'
[  4%] Building CXX object CMakeFiles/emulator.dir/src/address.cc.o
c++: error: unrecognized command line option ‘-Weverything’
CMakeFiles/emulator.dir/build.make:62: recipe for target 'CMakeFiles/emulator.dir/src/address.cc.o' failed
make[3]: *** [CMakeFiles/emulator.dir/src/address.cc.o] Error 1
make[3]: Leaving directory '/home/fuwangqin/code/emulator/build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/emulator.dir/all' failed
make[2]: *** [CMakeFiles/emulator.dir/all] Error 2
make[2]: Leaving directory '/home/fuwangqin/code/emulator/build'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/fuwangqin/code/emulator/build'
Makefile:16: recipe for target 'compile' failed
make: *** [compile] Error 2
fuwangqin@fuwangqin-pc:\~/code/emulator$

**Comment by jgilchrist** [comment]
Thanks for filing this @akzi! I've been developing this using clang so there may be some issues when trying to compile it with gcc. I've been planning to make some changes so it can be built with both, but in the meantime if you manage to get it to build on gcc please feel free to submit a pull request!

**Comment by jgilchrist** [comment]
@akzi If you're still interested in this, the most recently merged pull request adds support for building with gcc!
