### ISSUE TITLE
test with https://github.com/drhelius/demo-emulator/blob/master/test_roms/cpu_instrs/cpu_instrs.gb,something error happend?

### ISSUE THREAD

**Issue by akzi** [jgilchrist/emulator#2]
| Attempting to read from cartridge RAM
| Attempting to read from cartridge RAM
| Attempting to read from cartridge RAM
| Attempting to read from cartridge RAM
| Attempting to read from cartridge RAM
| Attempting to read from cartridge RAM
| Attempting to read from cartridge RAM
| Attempting to read from cartridge RAM
| Attempting to read from cartridge RAM
| Attempting to read from cartridge RAM
| Attempting to read from cartridge RAM
| Attempting to read from cartridge RAM
| Attempting to read from cartridge RAM
| Attempting to read from cartridge RAM
| Attempting to read from cartridge RAM
| Attempting to read from cartridge RAM
| Attempting to read from cartridge RAM
| Attempting to read from cartridge RAM
| Attempting to read from cartridge RAM
| Boot rom was disabled
| Wrote to sound on/off address 0xff26 - 0x0
| Wrote to sound on/off address 0xff26 - 0x80
| Wrote to selection of sound output terminal address 0xff25 - 0xff
| Wrote to channel control address 0xff24 - 0x77
cpu_instrs

| Attempting to write to cartridge ROM: 2000 - 0x1
01| Wrote to sound on/off address 0xff26 - 0x0
| Wrote to sound on/off address 0xff26 - 0x80
| Wrote to selection of sound output terminal address 0xff25 - 0xff
| Wrote to channel control address 0xff24 - 0x77
:ok  | Attempting to write to cartridge ROM: 2000 - 0x1
02| Wrote to sound on/off address 0xff26 - 0x0
| Wrote to sound on/off address 0xff26 - 0x80
| Wrote to selection of sound output terminal address 0xff25 - 0xff
| Wrote to channel control address 0xff24 - 0x77
| Wrote to unknown address 0xff05 - 0x0
:04  | Attempting to write to cartridge ROM: 2000 - 0x1
03| Wrote to sound on/off address 0xff26 - 0x0
| Wrote to sound on/off address 0xff26 - 0x80
| Wrote to selection of sound output terminal address 0xff25 - 0xff
| Wrote to channel control address 0xff24 - 0x77
| Attempted to read from 'Prepare Speed Switch' register
| Attempted to write to 'Prepare Speed Switch' register
| Fatal error @ [opcode_stop:822]
| Stopped

**Comment by jgilchrist** [comment]
Hi @akzi - the emulator currently doesn't have MBC1 support which is required to run the `cpu_instrs.gb` test rom. It should, however, run all of the roms under the `individual/` folder ([here](https://github.com/drhelius/demo-emulator/tree/master/test_roms/cpu_instrs/individual)) aside from `interrupts.gb`.
