### ISSUE TITLE
Help output in debugger is misleading (registers should be regs)

### ISSUE THREAD

**Issue by r2p2** [jgilchrist/emulator#4]
When calling help within the debugger, we get the following output.
```
> help
...
= Debug Information
registers            Print a dump of the CPU registers
flags                Print a dump of the CPU flags
....
```

But the command to print a dump of the registers seems to be just `regs`.

**Comment by jgilchrist** [comment]
Thanks @r2p2, you're absolutely right! I've fixed this in a5c5c18.
