### ISSUE TITLE
AND also effecting F register

### ISSUE THREAD

**Issue by r2p2** [jgilchrist/emulator#5]
I do also wonder why `AND` touches the `F` register. 
```
| 0xC321: LD A,C (0x79)
> regs
AF: 0100
BC: 1301
DE: 1300
HL: C304
SP: DFFD
PC: C322
> step
| 0xC322: AND n (0xe6)
> regs
AF: 00A0
BC: 1301
DE: 1300
HL: C304
SP: DFFD
PC: C324
```

Any documentation I found only talks about `A`

**Comment by jgilchrist** [comment]
Hi @r2p2! I used [this site](http://www.pastraiser.com/cpu/gameboy/gameboy_opcodes.html) a lot while writing the opcdes - as you can see in the `Ax` row, the `AND` opcodes have the following effect on the flags:

```
        Flags affected:
            Z - Set if result is zero.
            N - Reset.
            H - Set.
            C - Reset.
```

**Comment by r2p2** [comment]
I did not realize, that the `F`register IS the flag register. Kept it separately until now...
Thank you and sorry.
