### ISSUE TITLE
debugger commands listed incorrectly under help

### ISSUE THREAD

**Issue by mattyg915** [jgilchrist/emulator#7]
In the debugger the command parser is looking for strings of mem or memcell in order to view a location or range in the virtual memory:

```
    if (cmd == "mem") return CommandType::Memory;
    if (cmd == "memcell") return CommandType::MemoryCell;
```

However, the help menu says to type "memory" or "memory cell":

```
    printf("memory $start $lines Print a dump of memory from $start to $end\n");
    printf("memorycell $addr     Print the value of the memory at $addr\n");
```

One or the other should be changed so that they matched. Selfishly, mem and memcell are faster to type.

**Comment by jgilchrist** [comment]
You're right, thanks for spotting that @mattyg915. I think I updated them all in the past (finding them too long to type when debugging) and neglected to update all of the docs.

Fixed in 08e38c3 and 18849c3.
